### ISSUE TITLE
grey is not showing

### ISSUE THREAD

**Issue by ahmedelgabri** [anunez/one-dark-iterm#1]
I found a minor issue similar to this [solarized problem](https://github.com/altercation/solarized/issues/220), especially when using Gulp _it is using [grey](https://github.com/js-cli/fancy-log/blob/master/index.js#L9) for the timestamp_

<img width="637" alt="screen shot 2015-11-09 at 23 20 03" src="https://cloud.githubusercontent.com/assets/63876/11048525/b1b39f40-8738-11e5-9095-297bd30155c8.png">

I had to change the contrast in iTerm2 settings to be able to see some info.
<img width="456" alt="screen shot 2015-11-09 at 23 19 48" src="https://cloud.githubusercontent.com/assets/63876/11048539/c6eed37a-8738-11e5-8f15-933306e933ef.png">

**Comment by anunez** [comment]
@ahmedelgabri yes, it's an issue of iTerm itself. As you said, you need to change the "Minimum contrast" setting in iTerm preferences. I'll leave a screenshot here for anyone else who may find this problem:

<img width="1036" alt="screen shot 2015-12-18 at 10 41 54" src="https://cloud.githubusercontent.com/assets/144149/11893906/2ddaeb06-a574-11e5-88cb-18ec367b15e5.png">
